name: "Publish"
on:
  push:
    paths:
      version.txt

jobs:
  sign:
    name: "Release Firefox Add-on"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup Node and Cache"
        uses: actions/setup-node@v4
      - name: "Install Dependencies"
        run: npm install --global web-ext
      - name: "Lint and Build"
        run: npm run prepare:firefox && npm run lint
      - name: "Publish to AMO"
        # run: npm run publish:firefox
        run: web-ext sign --api-key $AMO_SIGN_KEY --api-secret $AMO_SIGN_SECRET --channel unlisted
        env:
          AMO_SIGN_KEY: ${{ secrets.AMO_SIGN_KEY }}
          AMO_SIGN_SECRET: ${{ secrets.AMO_SIGN_SECRET }}